services:
  php:
    container_name: 'container_name_php'
    depends_on:
        - db
    networks:
      - my_network
    build:
      context: ./docker
    volumes:
      - '.:/var/www/html'
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    working_dir: '/var/www/html'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    container_name: 'container_name_nginx'
    image: nginx:1.23.2-alpine
    networks:
      - my_network
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - '.:/var/www/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'

  db:
    container_name: 'container_name_db'
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data: