apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony-app
  template:
    metadata:
      labels:
        app: symfony-app
    spec:
      containers:
        - name: app
          image: adminvitcon/k8s-php-sceleton:1.0.2
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql://db_user:db_password@postgres-db:5432/db_name?serverVersion=13&charset=utf8"

---
apiVersion: v1
kind: Service
metadata:
  name: symfony-app
spec:
  selector:
    app: symfony-app
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP