apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name skeleton.local;
      root /var/www/html/public;
      index index.php index.html index.htm;

      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";

      location / {
        try_files $uri /index.php$is_args$args;
      }

      location ~ \.php$ {
          fastcgi_pass symfony-app:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $realpath_root;
          include fastcgi_params;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;
      }
    }
