apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Размер хранилища
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: symfony-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/home/sites/kub8s/symfony-k8s/public  # ваш локальный путь
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi