#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pgdata-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi # Размер хранилища
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: symfony-pv
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/www/html  # ?ваш локальный путь
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-pvc
spec:
  storageClassName: default
  volumeMode: Filesystem
  volumeName: symfony-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi