apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "db_name"
            - name: POSTGRES_USER
              value: "db_user"
            - name: POSTGRES_PASSWORD
              value: "db_password"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data # Место хранения данных
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata-pvc # PVC для хранения данных
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-db
  type: ClusterIP # Доступ внутри кластера