apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: adminvitcon/k8s-nginx-not-http-sceleton:1.0.2
          ports:
            - containerPort: 80
              protocol: TCP
#          env:
#            - name: APP_NAME
#              value: "symfony-app"
          volumeMounts:
            - name: symfony-storage
              mountPath: /var/www/html/public # проект в контейнере
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf # расположение конфигурационного файла
              subPath: default.conf # имя файла из ConfigMap
      volumes:
        - name: symfony-storage
          persistentVolumeClaim:
            claimName: symfony-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer